package fpinscala.parsing

import fpinscala.generative_testing.Prop.forAll
import fpinscala.generative_testing.{Gen, Prop}

import scala.annotation.tailrec
import scala.util.matching.Regex

trait Parsers[Parser[+_]] {
  self =>
  // Primitives
  // Slice will return the string representation of the input parsed by given parser
  def slice[A](p: Parser[A]): Parser[String]
  // 9.7 Implement map2 and product using flatMap
  def flatMap[A, B](p: Parser[A])(f: A => Parser[B]): Parser[B]
  // Runs parser p1, if parser p1 fails in an uncommitted state, it runs parser p2
  // if it fails in an uncommitted state, it will fail with the error of parser p1
  def or[A](p1: Parser[A], p2: => Parser[A]): Parser[A]
  // Returns a parser that parsers string s literally
  implicit def string(s: String): Parser[String]
  // Returns a string parser that parses a string following the the regular expression pattern, r
  implicit def regex(r: Regex): Parser[String]
  // Labels a parser with an error message, msg, that will be returned if the parser fails
  def label[A](msg: String)(p: Parser[A]): Parser[A]
  // Labels a parser with an error message, msg, that will be returned if the parser fails stacked
  // on top of the original error message generated by the parser
  def scope[A](msg: String)(p: Parser[A]): Parser[A]
  // By default a parser will commit after successfully parsing one input character. Attempt delays
  // committing to a parser until after successful parsing
  def attempt[A](p: Parser[A]): Parser[A]

  def char(c: Char): Parser[Char] = string(c.toString) map (_.charAt(0))

  def succeed[A](a: A): Parser[A]

  def run[A](p: Parser[A])(input: String): Either[ParseError, A]

  def listOfN[A](p: Parser[A], n: Int): Parser[List[A]] = {
    @tailrec
    def go(p: Parser[A], n: Int, acc: Parser[List[A]]): Parser[List[A]] =
      if (n <= 0) acc
      else go(p, n - 1, map2(acc, p)((list, a) => a :: list))

    go(p, n, succeed(List.empty))
  }

  // 9.1 define many with map2
  def many[A](p: Parser[A]): Parser[List[A]] =
    map2(p, many(p))(_ :: _) or succeed(List())

  // 9.1 define many1 with many
  def many1[A](p: Parser[A]): Parser[List[A]] =
    map2(p, many(p))(_ :: _)

  // 9.8 Implement map using flatMap
  def map[A, B](p: Parser[A])(f: A => B): Parser[B] =
    p.flatMap(f andThen succeed)

  // Combines two parsers assuming the first is successful
  def product[A, B](p1: Parser[A], p2: => Parser[B]): Parser[(A, B)] =
    p1.flatMap(a => p2.map(b => (a, b)))

  def unbiasLeft[A, B, C](p: Parser[((A, B), C)]): Parser[(A, B, C)] =
    p.map(t => (t._1._1, t._1._2, t._2))

  def unbiasRight[A, B, C](p: Parser[(A, (B, C))]): Parser[(A, B, C)] =
    p.map(t => (t._1, t._2._1, t._2._2))

  // 9.1 Define a method map2 using product to combine two parsers
  def map2[A, B, C](p1: Parser[A], p2: Parser[B])(f: (A, B) => C): Parser[C] =
    for {a <- p1; b <- p2} yield f(a, b)

  def map3[A, B, C, D](p1: Parser[A], p2: Parser[B], p3: Parser[C])(f: (A, B, C) => D): Parser[D] =
    unbiasLeft(product(product(p1, p2), p3)).map(f.tupled)

  def wrap[A, B, C](prefix: Parser[A], suffix: Parser[C])(p: Parser[B]): Parser[B] =
    map3(prefix, p, suffix)((_, p, _) => p)

  lazy val numA: Parser[Int] = char('a').many.slice.map(_.length)
  lazy val numAsBs: Parser[(Int, Int)] =
    char('a').many.slice.map(_.length) **
      char('b').many1.slice.map(_.length)
  // 9.6 Use flatMap to write a context-sensensitive parser that can parse a number, n, followed
  // by n times the character for example "0" and "4aaaa"
  lazy val nNumAs: Parser[String] =
  digit
    .flatMap(n => listOfN(char('a'), n.toInt))
    .map(_.mkString)

  def whitespace: Parser[String] = """\s*""".r

  def digit: Parser[String] = """\d""".r

  def integer: Parser[String] = digit.many1.slice

  def double: Parser[String] = map3(integer, string("."), integer)(_ + _ + _)

  // Exponential numbers can be optimized by adding some way to add an optional suffix
  def expInteger: Parser[String] = map3(integer, """[eE]""".r, integer)(_ + _ + _)

  def expDouble: Parser[String] = map3(double, """[eE]""".r, integer)(_ + _ + _)

  // Will parse integers and doubles
  def plainNumber: Parser[String] =
    integer or double

  def expNumber: Parser[String] =
    expInteger or expDouble

  def signed: Parser[String] =
    regex("""[-+]?""".r)

  def number: Parser[String] =
    map2(signed, plainNumber)(_ + _) or map2(signed, plainNumber)(_ + _)

  def ignoreWhiteSpace[A](p1: Parser[A]): Parser[A] = wrap(whitespace, whitespace)(p1)

  implicit def operators[A](p: Parser[A]): ParserOps[A] = ParserOps(p)

  implicit def asStringParser[A](a: A)(implicit f: A => Parser[String]): ParserOps[String] =
    ParserOps(f(a))

  // Error message that depends on the contents of ParseError
  def errorMessage(p: ParseError): String

  def errorLocation(p: ParseError): Location

  case class ParserOps[A](p1: Parser[A]) {
    def |[B >: A](p2: Parser[B]): Parser[B] = self.or(p1, p2)

    def **[B](p2: Parser[B]): Parser[(A, B)] = self.product(p1, p2)

    def product[B](p2: Parser[B]): Parser[(A, B)] = self.product(p1, p2)

    def or[B >: A](p2: => Parser[B]): Parser[B] = self.or(p1, p2)

    def many: Parser[List[A]] = self.many(p1)

    def many1: Parser[List[A]] = self.many1(p1)

    def slice: Parser[String] = self.slice(p1)

    def map[B](f: A => B): Parser[B] = self.map(p1)(f)

    def map2[B, C](p2: Parser[B])(f: (A, B) => C): Parser[C] = self.map2(p1, p2)(f)

    def flatMap[B](f: A => Parser[B]): Parser[B] = self.flatMap(p1)(f)
  }

  object Laws {
    def equal[A](p1: Parser[A], p2: Parser[A])(in: Gen[String]): Prop =
      forAll(in)(s => run(p1)(s) == run(p2)(s))

    def mapLaw[A](p: Parser[A])(in: Gen[String]): Prop =
      equal(p, p.map(identity))(in)

    def succeedLaw[A](in: Gen[String]): Prop =
      forAll(in)(s => run(succeed(s))(s) == Right(s))

    def productAssociativityLaw[A, B, C](p1: Parser[A], p2: Parser[B], p3: Parser[C])(in: Gen[String]): Prop =
      equal(product(p1, product(p2, p3)).map(t => (t._1, t._2._1, t._2._2)),
        product(product(p1, p2), p3).map(t => (t._1, t._1._2, t._2)))(in)

    def productMapLaw[A, B](p1: Parser[A], p2: Parser[A])(f: A => B)(in: Gen[String]): Prop =
      equal(p1.map(f) ** p2.map(f), p1 ** p2 map { case (a, b) => (f(a), f(b)) })(in)
  }

}

case class ParseError(stack: List[(Location, String)] = List.empty) {
  def push(msg: String, location: Location): ParseError =
    copy((location, msg) :: stack)

  def label(msg: String): ParseError =
    ParseError(latestLoc.map((_, msg)).toList)

  def latest: Option[(Location, String)] = stack.lastOption

  def latestLoc: Option[Location] =
    latest.map(_._1)
}

case class Location(s: String, offSet: Int) {
  lazy val line: Int = s.slice(0, offSet + 1).count(_ == '\n') + 1

  lazy val col: Int = s.slice(0, offSet + 1).lastIndexOf("\n") match {
    case -1 => offSet + 1
    case lastLineIndex => offSet - lastLineIndex
  }
}

object Parsers {
  type MyParser[+A] = ParserState => ParserResult[A]

  sealed trait ParserResult[+A]
  final case class Success[+A](a: A, parsed: String) extends ParserResult[A]
  final case class Failure(get: ParseError, isCommitted: Boolean = false) extends ParserResult[Nothing] {
    def commit: Failure = Failure(get: ParseError, true)
    def uncommit: Failure = Failure(get: ParseError)
  }

  sealed trait ParserState {
    def input: String
    def parsed: String
    def offSet: Int
    def moveParser(size: Int) : ParserState
  }

  final case class Parsable(s: String, offSet: Int = 0) extends ParserState {
    override def input: String = s.substring(offSet)

    override def moveParser(size: Int): ParserState = Parsable(s, offSet + size)

    override def parsed: String = s.substring(0, offSet)
  }

  object MyParsers extends Parsers[MyParser] {
    override def slice[A](p: MyParser[A]): MyParser[String] = state => p(state) match {
      case Success(_, parsed) => Success(parsed, parsed)
      case f: Failure => Failure(f.get, f.isCommitted)
    }

    override def flatMap[A, B](p: MyParser[A])(f: A => MyParser[B]): MyParser[B] = state => p(state) match {
      case Success(a, parsed) =>
        f(a)(state.moveParser(parsed.length)) match {
          case Success(a2, parsed2) => Success(a2, parsed + parsed2)
          case failure => failure
        }
      case failure: Failure => failure
    }

    override def or[A](p1: MyParser[A], p2: => MyParser[A]): MyParser[A] = state => p1(state) match {
      case f: Failure =>
        if (f.isCommitted) f.uncommit
        else p2(state)
      case success => success
    }

    override implicit def string(s: String): MyParser[String] = state => {
      if (state.input.startsWith(s)) Success(s, s)
      else Failure(ParseError().push(s"Expects $s, but got ${state.input}", Location(state.input, state.offSet)))
    }

    override implicit def regex(r: Regex): MyParser[String] = state => r.findPrefixOf(state.input) match {
      case Some(s) => Success(s, s)
      case None => Failure(ParseError().push(s"Expects ${r.toString()}, but got ${state.input}", Location(state.input, state.offSet)))
    }

    override def label[A](msg: String)(p: MyParser[A]): MyParser[A] = state => p(state) match {
      case f: Failure => Failure(f.get.label(msg))
      case success => success
    }

    override def scope[A](msg: String)(p: MyParser[A]): MyParser[A] = state => p(state) match {
      case f: Failure => Failure(f.get.push(msg, f.get.latestLoc.get))
      case success => success
    }

    override def attempt[A](p: MyParser[A]): MyParser[A] = state => p(state) match {
      case f: Failure => f.commit
      case success => success
    }

    override def run[A](p: MyParser[A])(input: String): Either[ParseError, A] =
      p(Parsable(input)) match {
        case Success(a, s) =>
          if (s == input) Right(a)
          else Left(ParseError().push(s"Could not parse entire input. Parsed:\n$s\n Input: $input", Location(input, s.length)))
        case Failure(parseError, _) => Left(parseError)
      }

    override def errorMessage(p: ParseError): String = ???

    override def errorLocation(p: ParseError): Location = ???

    override def succeed[A](a: A): MyParser[A] = _ => Success(a, "")

  /* From: https://github.com/fpinscala/fpinscala/blob/master/answers/src/main/scala/fpinscala/parsing/instances/Reference.scala#L134
   */
    override def many[A](p: MyParser[A]): MyParser[List[A]] =
      s => {
        val buf = new collection.mutable.ListBuffer[A]
        def go(p: MyParser[A], parsed: String): ParserResult[List[A]] = {
          p(s.moveParser(parsed.length)) match {
            case Success(a, parsed2) => buf += a; go(p, parsed+parsed2)
            case f@Failure(_, true) => f
            case Failure(_, _) => Success(buf.toList,parsed)
          }
        }
        go(p, "")
      }
  }

  def jsonParser[Parser[+_]](P: Parsers[Parser]): Parser[JSON] = {
    import P._

    val openBrace = string("{")
    val closeBrace = string("}")
    val openBracket = ignoreWhiteSpace(string("["))
    val closeBracket = ignoreWhiteSpace(string("]"))
    val comma = ignoreWhiteSpace(string(","))
    def arr[A](p: Parser[A]) =
      wrap(openBracket, closeBracket)(p)
    def obj[A](p: Parser[A]) =
      wrap(openBrace, closeBrace)(p)
    def boolean: Parser[JBool] = string("true").map(_ => JBool(true)) or string("false").map(_ => JBool(false))
    def nill: Parser[JNull.type] = string("null").map(_ => JNull)
    def value: Parser[JSON] =
      nill or boolean or stringLiteral or nr or jarray or jobject
    def stringLiteral: Parser[JString] =
      map3(string("\""), """\w*""".r, string("\""))((_, s, _) => JString(s))
    def nr: Parser[JSON] =
      number.map(s => JNumber(s.toDouble))
    def element: Parser[JSON] =
      ignoreWhiteSpace(value)
    def elements: Parser[JArray] =
      map2(element, many(comma ** element))((json, a) => {
        if (a.isEmpty) JArray(List(json))
        else JArray(json :: a.map(_._2))
      })
    def jarray: Parser[JArray] =
      arr(elements) or
        map2(openBracket, closeBracket)((_, _) => JArray(List.empty))
    def member: Parser[(String, JSON)] =
      map3(ignoreWhiteSpace(stringLiteral), string(":"), element)((a, _, c) => (a.get, c))
    def members: Parser[JObject] =
      map2(member, many(comma ** member))((json, a) => {
        if (a.isEmpty) JObject(Map(json))
        else JObject((json :: a.map(_._2)).toMap)
      })
    def jobject: Parser[JSON] =
      obj(members) or
        obj(string("")).map(_ => JObject(Map.empty))

    element
  }

  sealed trait JSON
  case object JNull extends JSON
  case class JNumber(get: Double) extends JSON
  case class JBool(get: Boolean) extends JSON
  case class JString(get: String) extends JSON
  case class JArray(get: List[JSON]) extends JSON
  case class JObject(get: Map[String, JSON]) extends JSON
}
